// packages/angular/src/app/app.component.ts
import { Component, EventEmitter, Input, Output, VERSION } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  count = 0;
  version = VERSION.full;

  @Input()
  name = '';

  @Output()
  nameChange = new EventEmitter<string>();

  onInput(e: KeyboardEvent): void {
    const input = e.currentTarget as HTMLInputElement;
    this.count++;
    this.nameChange.emit(input.value);
  }
}

<h1>Angular {{ version }}</h1>
Current name is <code>{{ name }}</code>
<label>
  Type to change name <input [value]="name" (input)="onInput($event)" />
</label>
<p>
  Changed internally <code>{{ count }}</code> times
</p>

// packages/svelte/src/App.svelte
<script lang="ts">
  export let name: string;
  export let onNameChange: (name: string) => void;

  let count = 0;

  function onInput(e: Event) {
    const input = e.currentTarget as HTMLInputElement;
    count++;
    onNameChange(input.value);
  }
</script>

<h1>Svelte</h1>
Current name is
<code>{name}</code>
<label>Type to change name <input value={name} on:input={onInput} /></label>
<p>Changed internally <code>{count}</code> times</p>
