// packages/svelte/src/App.svelte
<script lang="ts">
  export let name: string;
  export let onNameChange: (name: string) => void;

  let count = 0;

  function onInput(e: Event) {
    const input = e.currentTarget as HTMLInputElement;
    count++;
    onNameChange(input.value);
  }
</script>

<h1>Svelte</h1>
Current name is
<code>{name}</code>
<label>Type to change name <input value={name} on:input={onInput} /></label>
<p>Changed internally <code>{count}</code> times</p>

// packages/react/App.tsx
import React, { useState, version } from 'react';

interface Props {
  name: string;
  onNameChange: (name: string) => void;
}

export const App = ({ name, onNameChange }: Props) => {
  const [count, setCount] = useState(0);

  return (
    <>
      <h1>React {version}</h1>
      Current name is <code>{name}</code>
      <label>
        Type to change name
        <input
          value={name}
          onChange={(e) => {
            const input = e.currentTarget as HTMLInputElement;
            setCount(count + 1);
            onNameChange(input.value);
          }}
        />
      </label>
      <p>
        Changed internally <code>{count}</code> times
      </p>
    </>
  );
};
